trigger:
  branches:
    include:
      - dev
      - release/prod

stages:
  - stage: Build
    displayName: Build React App
    jobs:
      - job: Build
        pool:
          vmImage: ubuntu-latest
        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: '20.x'

          - script: |
              cd react-azure-devops
              npm install
              npm run build
            displayName: 'Install & Build'

          - task: ArchiveFiles@2
            displayName: 'Archive build files'
            inputs:
              rootFolderOrFile: 'react-azure-devops/dist'
              includeRootFolder: false
              archiveType: 'zip'
              archiveFile: '$(Build.ArtifactStagingDirectory)/react-build.zip'
              replaceExistingArchive: true

          - task: PublishPipelineArtifact@1
            inputs:
              targetPath: '$(Build.ArtifactStagingDirectory)/react-build.zip'
              artifact: 'react-build'

  - stage: Deploy_Dev
    displayName: Deploy to DEV
    dependsOn: Build
    jobs:
      - deployment: DeployDev
        environment: 'dev'
        pool:
          vmImage: ubuntu-latest
        strategy:
          runOnce:
            deploy:
              steps:
                - download: current
                  artifact: react-build

                - task: AzureWebApp@1
                  inputs:
                    azureSubscription: 'azure-service-connection'
                    appType: 'webAppLinux'
                    appName: 'haseeb-react-dev'
                    package: '$(Pipeline.Workspace)/react-build/react-build.zip'
                    appSettings: '-SCM_DO_BUILD_DURING_DEPLOYMENT false'

  - stage: Deploy_Prod
    displayName: Deploy to PROD
    dependsOn: Deploy_Dev
    condition: eq(variables['Build.SourceBranch'], 'refs/heads/release/prod')
    jobs:
      - deployment: DeployProd
        environment: 'production'
        pool:
          vmImage: ubuntu-latest
        strategy:
          runOnce:
            deploy:
              steps:
                - download: current
                  artifact: react-build

                - task: AzureWebApp@1
                  inputs:
                    azureSubscription: 'azure-service-connection'
                    appType: 'webAppLinux'
                    appName: 'haseeb-react-prod'
                    package: '$(Pipeline.Workspace)/react-build/react-build.zip'
                    appSettings: '-SCM_DO_BUILD_DURING_DEPLOYMENT false'
            