trigger:
  branches:
    include:
      - dev

stages:
  - stage: Build
    displayName: Build React App
    jobs:
      - job: Build
        pool:
          vmImage: ubuntu-latest
        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: '20.x'

          - script: |
              cd react-azure-devops
              npm install
              npm run build
            displayName: Install & Build

          - task: PublishPipelineArtifact@1
            inputs:
              targetPath: 'react-azure-devops/dist'
              artifact: 'react-build'

  - stage: Deploy_Dev
    displayName: Deploy to DEV
    dependsOn: Build
    jobs:
      - deployment: DeployDev
        environment: dev
        pool:
          vmImage: ubuntu-latest
        strategy:
          runOnce:
            deploy:
              steps:
                - download: current
                  artifact: react-build

                - task: AzureWebApp@1
                  inputs:
                    azureSubscription: 'azure-service-connection'
                    appType: 'webApp'
                    appName: 'haseeb-react-dev'
                    package: '$(Pipeline.Workspace)/react-build'